# Generated by Django 4.2.11 on 2024-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_sampledata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleAgentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=100)),
                ("agent_name", models.CharField(max_length=100)),
                ("agent_code", models.IntegerField()),
                ("position_code", models.IntegerField()),
                ("certificate_number", models.CharField(max_length=100)),
            ],
        ),
    ]
