# Generated by Django 5.0.7 on 2024-08-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sampleagentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='agency_details',
            fields=[
                ('registration_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_code', models.IntegerField()),
                ('position_code', models.IntegerField()),
                ('certificate_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'agency_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('room_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=500)),
                ('floor', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('deposit', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('maintenance_fee', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('property_link', models.CharField(max_length=500)),
                ('registration_number', models.CharField(max_length=100)),
                ('agency_name', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('subway_count', models.IntegerField()),
                ('nearest_subway_distance', models.IntegerField()),
                ('store_count', models.IntegerField()),
                ('nearest_store_distance', models.IntegerField()),
                ('cafe_count', models.IntegerField()),
                ('nearest_cafe_distance', models.IntegerField()),
                ('market_count', models.IntegerField()),
                ('nearest_market_distance', models.IntegerField()),
                ('restaurant_count', models.IntegerField()),
                ('nearest_restaurant_distance', models.IntegerField()),
                ('hospital_count', models.IntegerField()),
                ('nearest_hospital_distance', models.IntegerField()),
                ('image_link', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SampleAgentData',
        ),
        migrations.AddField(
            model_name='sampledata',
            name='direction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
